version: '3.1'

services:

  db:
    image: postgis/postgis:13-3.1
      #    restart: always
    container_name: "postgres_defaultDb"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: defaultDb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    networks:
      - postgres-compose-network
            
networks: 
  postgres-compose-network:
    driver: bridge
volumes:
  data:
